<project xmlns="http://maven.apache.org/POM/4.0.0">

    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.skywatch</groupId>
        <artifactId>skywatch-platform</artifactId>
        <version>1.0.0</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <groupId>com.skywatch</groupId>
    <artifactId>common</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>


    <modules>
        <module>common-exception</module>
        <module>common-security</module>
        <module>common-kafka</module>
        <module>common-redis</module>
        <module>common-util</module>
    </modules>
</project>
